using System;

namespace ContextManagement
{
	/// <summary>
	/// Attach to public fields on a data model class to exclude them from the
	/// JSON schema generated by <see cref="JSONSchema.FromType"/>. The field is
	/// skipped entirely and will not appear in schema properties or be consumed
	/// by entity tools.
	/// </summary>
	/// <example>
	/// <code>
	/// public class CharacterData
	/// {
	///     [SchemaDescription("The character's display name.")]
	///     public string name;
	///
	///     [SchemaNonSerialized]
	///     public string internalId;
	/// }
	/// </code>
	/// </example>
	[AttributeUsage(AttributeTargets.Field, AllowMultiple = false)]
	public class SchemaNonSerializedAttribute : Attribute
	{
	}
}
