using System;

namespace ContextManagement
{
	/// <summary>
	/// Attach to public fields on a data model class to make them optional field of 
	/// JSON schema generated by <see cref="JSONSchema.FromType"/>.
	/// </summary>
	[AttributeUsage(AttributeTargets.Field, AllowMultiple = false)]
	public class SchemaOptionalAttribute : Attribute
	{
	}
}
